(() => {
  'use strict'

  const entries = [
    {
      id: 'prologue-declaration',
      stage: 'prologue',
      state: 0,
      triggerProgress: 0,
      spatialAnchor: 'hero-left-depth',
      enterBehavior: 'present-with-complete-spine',
      exitBehavior: 'occluded-by-approaching-surface',
      inheritedFrom: null,
      transformsInto: 'observation-name',
      kind: 'statement',
      lines: ['我试图穿过世界的表象，', '寻找未被命名的真实。'],
    },
    {
      id: 'observation-name',
      stage: 'observation',
      state: 1,
      triggerProgress: 0.64,
      spatialAnchor: 'mobius-surface-left',
      enterBehavior: 'emerge-from-surface',
      exitBehavior: 'recede-into-material',
      inheritedFrom: 'prologue-declaration',
      transformsInto: 'observation-thought-node',
      kind: 'stage-copy',
      eyebrow: '',
      title: '观象',
      body: '世界不断经过，只有真正被看见的事物才留下形状。',
    },
    {
      id: 'observation-new-fact',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.7,
      spatialAnchor: 'thought-route-new-fact',
      enterBehavior: 'cross-from-rear-depth',
      exitBehavior: 'fade-before-impact',
      inheritedFrom: null,
      transformsInto: 'observation-thought-node',
      kind: 'fragment', text: '一条新的事实进入视野', start: [-0.12, 0.2], end: [0.27, 0.39], size: 11, blur: 0.3, front: false,
    },
    {
      id: 'observation-existing-frame',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.72,
      spatialAnchor: 'thought-route-existing-frame',
      enterBehavior: 'cross-front-depth',
      exitBehavior: 'settle-as-optical-residue',
      inheritedFrom: null,
      transformsInto: 'observation-thought-node',
      kind: 'fragment', text: '已有经验提供第一种解释', start: [0.42, -0.14], end: [0.4, 0.31], size: 12, blur: 0.15, front: true,
    },
    {
      id: 'observation-prior-scale',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.74,
      spatialAnchor: 'thought-route-prior-scale',
      enterBehavior: 'cross-front-depth',
      exitBehavior: 'remain-as-shallow-relief',
      inheritedFrom: null,
      transformsInto: 'order-entering-node',
      kind: 'fragment', text: '旧知识给出另一种尺度', start: [1.12, 0.12], end: [0.62, 0.28], size: 12, blur: 0, front: true,
    },
    {
      id: 'observation-context',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.76,
      spatialAnchor: 'thought-route-context',
      enterBehavior: 'cross-rear-depth',
      exitBehavior: 'dissipate-without-imprint',
      inheritedFrom: null,
      transformsInto: null,
      kind: 'fragment', text: '情境改变了信息的方向', start: [1.1, 0.78], end: [0.77, 0.38], size: 10, blur: 0.7, front: false,
    },
    {
      id: 'observation-uncertain-relation',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.78,
      spatialAnchor: 'thought-route-uncertain',
      enterBehavior: 'cross-front-depth',
      exitBehavior: 'fade-before-impact',
      inheritedFrom: null,
      transformsInto: null,
      kind: 'fragment', text: '关系仍在形成', start: [-0.18, 0.88], end: [0.68, 0.55], size: 10, blur: 0.4, front: true,
    },
    {
      id: 'observation-contradiction',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.8,
      spatialAnchor: 'thought-route-contradiction',
      enterBehavior: 'cross-rear-depth',
      exitBehavior: 'remain-as-compression-mark',
      inheritedFrom: null,
      transformsInto: 'order-secondary-wall',
      kind: 'fragment', text: '矛盾保留了另一种可能', start: [1.15, 0.32], end: [0.49, 0.65], size: 12, blur: 0.2, front: false,
    },
    {
      id: 'observation-recurring-pattern',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.82,
      spatialAnchor: 'thought-route-pattern',
      enterBehavior: 'cross-rear-depth',
      exitBehavior: 'remain-as-deepening-groove',
      inheritedFrom: null,
      transformsInto: 'order-entering-node',
      kind: 'fragment', text: '重复使模式变得可见', start: [-0.2, 0.58], end: [0.36, 0.55], size: 12, blur: 0.25, front: false,
    },
    {
      id: 'observation-thought-node',
      stage: 'observation',
      state: 3,
      triggerProgress: 0.87,
      spatialAnchor: 'thought-node-origin',
      enterBehavior: 'continue-after-world-freezes',
      exitBehavior: 'press-into-bone-material',
      inheritedFrom: 'observation-prior-scale',
      transformsInto: 'order-entering-node',
      kind: 'fragment', text: '被真正看见', start: [1.12, 0.25], end: [0.5, 0.57], size: 14, blur: 0, front: true, weighted: true,
    },
    {
      id: 'order-name',
      stage: 'order',
      state: 5,
      triggerProgress: 0.33,
      spatialAnchor: 'bearing-wall-left',
      enterBehavior: 'rise-with-inherited-imprint',
      exitBehavior: 'become-structural-caption',
      inheritedFrom: 'observation-thought-node',
      transformsInto: 'order-generated-viewpoint',
      kind: 'stage-copy',
      eyebrow: '关系开始生成',
      title: '构序',
      body: '新信息与已有知识改变彼此的曲率，一个此前不存在的观点由关系生成。',
    },
    {
      id: 'order-generated-viewpoint',
      stage: 'order',
      state: 7,
      triggerProgress: 0.43,
      spatialAnchor: 'relationship-negative-space',
      enterBehavior: 'emerge-between-three-curving-surfaces',
      exitBehavior: 'remain-as-generated-system-viewpoint',
      inheritedFrom: 'order-name',
      transformsInto: 'reflection-name',
      kind: 'paired-thought',
      past: { year: '已有节点', text: '经验提供了可用的解释，' },
      present: { year: '新观点', text: '关系改变之后，解释的边界也随之改变。' },
    },
    {
      id: 'reflection-name',
      stage: 'reflection',
      state: 9,
      triggerProgress: 0.57,
      spatialAnchor: 'one-room-inner-surface',
      enterBehavior: 'appear-after-temporal-fold',
      exitBehavior: 'remain-as-room-observation',
      inheritedFrom: 'order-generated-viewpoint',
      transformsInto: 'reflection-room-years',
      kind: 'stage-copy',
      eyebrow: '系统开始观察自身',
      title: '观心',
      body: '当秩序开始回望，时间不再只是排列过去，也开始显露判断如何形成。',
    },
    {
      id: 'reflection-room-years',
      stage: 'reflection',
      state: 10,
      triggerProgress: 0.65,
      spatialAnchor: 'one-room-four-times',
      enterBehavior: 'replace-one-room-in-place',
      exitBehavior: 'reopen-system-interface',
      inheritedFrom: 'reflection-name',
      transformsInto: 'nature-name',
      kind: 'time-sequence',
      moments: [
        { year: '输入', text: '事实进入，尚未拥有解释' },
        { year: '经验', text: '旧知识参与了判断的形成' },
        { year: '关系', text: '矛盾与情境改变了它的方向' },
        { year: '此刻', text: '系统看见自己为何这样判断' },
      ],
    },
    {
      id: 'nature-name',
      stage: 'nature',
      state: 13,
      triggerProgress: 0.84,
      spatialAnchor: 'whole-spine-right',
      enterBehavior: 'align-after-total-reveal',
      exitBehavior: 'disperse-with-material-removal',
      inheritedFrom: 'reflection-room-years',
      transformsInto: 'final-question',
      kind: 'stage-copy',
      eyebrow: '观点融入自身',
      title: '见性',
      body: '新观点不再独立存在；它改变整体的运行方式，然后观察短暂安静。',
    },
    {
      id: 'final-question',
      stage: 'nature',
      state: 15,
      triggerProgress: 0.98,
      spatialAnchor: 'void-multiple-depths',
      enterBehavior: 'align-after-one-full-silence',
      exitBehavior: 'separate-on-renewed-motion',
      inheritedFrom: 'nature-name',
      transformsInto: 'next-observation-cycle',
      kind: 'question',
      lines: ['当判断暂时安静，', '你如何看见正在形成判断的自己？'],
    },
  ]

  window.SELF_AWAKE_CONTENT = Object.freeze({
    version: 1,
    stateLabels: Object.freeze([
      '首页 · 完整骨架',
      '观象 · 显名',
      '观象 · 信息经过',
      '观象 · 节点被吸收',
      '转场 · 节点进入关系',
      '构序 · 归类',
      '构序 · 曲率趋同',
      '构序 · 新观点生成',
      '转场 · 进入曲面厚度',
      '观心 · 旧状态',
      '观心 · 时间重现',
      '观心 · 空间回望',
      '转场 · 新观点融入整体',
      '见性 · 更新后的整体',
      '见性 · 逐层剥离',
      '见性 · 最终返照',
    ]),
    entries: Object.freeze(entries.map((entry) => Object.freeze(entry))),
  })
})()
