(() => {
  'use strict'

  const entries = [
    {
      id: 'prologue-declaration',
      stage: 'prologue',
      state: 0,
      triggerProgress: 0,
      spatialAnchor: 'hero-left-depth',
      enterBehavior: 'present-with-complete-spine',
      exitBehavior: 'occluded-by-approaching-surface',
      inheritedFrom: null,
      transformsInto: 'observation-name',
      kind: 'statement',
      lines: ['我试图穿过世界的表象，', '寻找未被命名的真实。'],
    },
    {
      id: 'observation-name',
      stage: 'observation',
      state: 1,
      triggerProgress: 0.64,
      spatialAnchor: 'mobius-surface-left',
      enterBehavior: 'emerge-from-surface',
      exitBehavior: 'recede-into-material',
      inheritedFrom: 'prologue-declaration',
      transformsInto: 'observation-weighted-imprint',
      kind: 'stage-copy',
      eyebrow: '',
      title: '观象',
      body: '世界不断经过，只有真正被看见的事物才留下形状。',
    },
    {
      id: 'observation-photo',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.7,
      spatialAnchor: 'route-node-photo',
      enterBehavior: 'cross-from-rear-depth',
      exitBehavior: 'fade-before-impact',
      inheritedFrom: null,
      transformsInto: 'observation-weighted-imprint',
      kind: 'fragment', text: '未保存的照片', start: [-0.12, 0.2], end: [0.27, 0.39], size: 11, blur: 0.3, front: false,
    },
    {
      id: 'observation-light-edge',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.72,
      spatialAnchor: 'route-node-light',
      enterBehavior: 'cross-front-depth',
      exitBehavior: 'settle-as-optical-residue',
      inheritedFrom: null,
      transformsInto: 'observation-weighted-imprint',
      kind: 'fragment', text: '光先留下边缘', start: [0.42, -0.14], end: [0.4, 0.31], size: 12, blur: 0.15, front: true,
    },
    {
      id: 'observation-question-2023',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.74,
      spatialAnchor: 'route-node-question',
      enterBehavior: 'cross-front-depth',
      exitBehavior: 'remain-as-shallow-relief',
      inheritedFrom: null,
      transformsInto: 'order-bearing-axis',
      kind: 'fragment', text: '2023 · 问题第一次出现', start: [1.12, 0.12], end: [0.62, 0.28], size: 12, blur: 0, front: true,
    },
    {
      id: 'observation-rain',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.76,
      spatialAnchor: 'route-node-rain',
      enterBehavior: 'cross-rear-depth',
      exitBehavior: 'dissipate-without-imprint',
      inheritedFrom: null,
      transformsInto: null,
      kind: 'fragment', text: '雨向玻璃左侧', start: [1.1, 0.78], end: [0.77, 0.38], size: 10, blur: 0.7, front: false,
    },
    {
      id: 'observation-unsent',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.78,
      spatialAnchor: 'route-node-unsent',
      enterBehavior: 'cross-front-depth',
      exitBehavior: 'fade-before-impact',
      inheritedFrom: null,
      transformsInto: null,
      kind: 'fragment', text: '04:17 · 句子没有寄出', start: [-0.18, 0.88], end: [0.68, 0.55], size: 10, blur: 0.4, front: true,
    },
    {
      id: 'observation-old-wall',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.8,
      spatialAnchor: 'route-node-wall',
      enterBehavior: 'cross-rear-depth',
      exitBehavior: 'remain-as-compression-mark',
      inheritedFrom: null,
      transformsInto: 'order-secondary-wall',
      kind: 'fragment', text: '旧墙的裂口', start: [1.15, 0.32], end: [0.49, 0.65], size: 12, blur: 0.2, front: false,
    },
    {
      id: 'observation-repeated-question',
      stage: 'observation',
      state: 2,
      triggerProgress: 0.82,
      spatialAnchor: 'route-node-repetition',
      enterBehavior: 'cross-rear-depth',
      exitBehavior: 'remain-as-deepening-groove',
      inheritedFrom: null,
      transformsInto: 'order-bearing-axis',
      kind: 'fragment', text: '反复出现的问题', start: [-0.2, 0.58], end: [0.36, 0.55], size: 12, blur: 0.25, front: false,
    },
    {
      id: 'observation-weighted-imprint',
      stage: 'observation',
      state: 3,
      triggerProgress: 0.87,
      spatialAnchor: 'master-scar-origin',
      enterBehavior: 'continue-after-world-freezes',
      exitBehavior: 'press-into-bone-material',
      inheritedFrom: 'observation-question-2023',
      transformsInto: 'order-bearing-axis',
      kind: 'fragment', text: '真正看见', start: [1.12, 0.25], end: [0.5, 0.57], size: 14, blur: 0, front: true, weighted: true,
    },
    {
      id: 'order-name',
      stage: 'order',
      state: 5,
      triggerProgress: 0.33,
      spatialAnchor: 'bearing-wall-left',
      enterBehavior: 'rise-with-inherited-imprint',
      exitBehavior: 'become-structural-caption',
      inheritedFrom: 'observation-weighted-imprint',
      transformsInto: 'order-cross-time-thought',
      kind: 'stage-copy',
      eyebrow: '痕迹开始承重',
      title: '构序',
      body: '痕迹不再只是被保存；它们开始决定彼此的方向、尺度与距离。',
    },
    {
      id: 'order-cross-time-thought',
      stage: 'order',
      state: 7,
      triggerProgress: 0.43,
      spatialAnchor: 'paired-bearing-surfaces',
      enterBehavior: 'appear-on-separated-surfaces',
      exitBehavior: 'align-once-at-time-fold',
      inheritedFrom: 'order-name',
      transformsInto: 'reflection-name',
      kind: 'paired-thought',
      past: { year: '2021', text: '我以为答案藏在更完整的系统里，' },
      present: { year: '2026', text: '后来才明白，系统只是问题改变承重的方式。' },
    },
    {
      id: 'reflection-name',
      stage: 'reflection',
      state: 9,
      triggerProgress: 0.57,
      spatialAnchor: 'one-room-inner-surface',
      enterBehavior: 'appear-after-temporal-fold',
      exitBehavior: 'remain-as-room-observation',
      inheritedFrom: 'order-cross-time-thought',
      transformsInto: 'reflection-room-years',
      kind: 'stage-copy',
      eyebrow: '系统开始观察自身',
      title: '观心',
      body: '当秩序开始回望，时间不再只是排列过去，也开始显露判断如何形成。',
    },
    {
      id: 'reflection-room-years',
      stage: 'reflection',
      state: 10,
      triggerProgress: 0.65,
      spatialAnchor: 'one-room-four-times',
      enterBehavior: 'replace-one-room-in-place',
      exitBehavior: 'reopen-system-interface',
      inheritedFrom: 'reflection-name',
      transformsInto: 'nature-name',
      kind: 'time-sequence',
      moments: [
        { year: '2019', text: '只有轮廓，判断尚未成形' },
        { year: '2022', text: '关系出现，矛盾仍被保存' },
        { year: '2026', text: '结构看似终于完整' },
        { year: '此刻', text: '我经过以后，系统再次打开' },
      ],
    },
    {
      id: 'nature-name',
      stage: 'nature',
      state: 13,
      triggerProgress: 0.84,
      spatialAnchor: 'whole-spine-right',
      enterBehavior: 'align-after-total-reveal',
      exitBehavior: 'disperse-with-material-removal',
      inheritedFrom: 'reflection-room-years',
      transformsInto: 'final-question',
      kind: 'stage-copy',
      eyebrow: '内外原来同面',
      title: '见性',
      body: '我始终向前，却回到了开始；所谓内外，从来没有两面。',
    },
    {
      id: 'final-question',
      stage: 'nature',
      state: 15,
      triggerProgress: 0.98,
      spatialAnchor: 'void-multiple-depths',
      enterBehavior: 'align-after-one-full-silence',
      exitBehavior: 'separate-on-renewed-motion',
      inheritedFrom: 'nature-name',
      transformsInto: 'next-observation-cycle',
      kind: 'question',
      lines: ['当所有可以证明的结构都退去，', '你仍愿意为哪一个选择负责？'],
    },
  ]

  window.SELF_AWAKE_CONTENT = Object.freeze({
    version: 1,
    stateLabels: Object.freeze([
      '首页 · 完整骨架',
      '观象 · 显名',
      '观象 · 信息经过',
      '观象 · 印痕留下',
      '转场 · 印痕成为轴线',
      '构序 · 归类',
      '构序 · 空间邻接',
      '构序 · 跨时间对齐',
      '转场 · 进入曲面厚度',
      '观心 · 旧状态',
      '观心 · 时间重现',
      '观心 · 空间回望',
      '转场 · 曲面开始回收',
      '见性 · 整体显现',
      '见性 · 逐层剥离',
      '见性 · 最终返照',
    ]),
    entries: Object.freeze(entries.map((entry) => Object.freeze(entry))),
  })
})()
