(function () {
  const content = {
    brand: {
      name: 'self-awake',
      alternate: 'self-awareness',
      statement: '我试图穿过世界的表象，寻找未被命名的真实。',
      statementEn: 'I move through appearances, looking for what has not yet been named.',
      privacy: '阅读痕迹只保存在当前浏览器，不上传，也不属于任何人群。',
    },
    layers: [
      { id: 'core', index: '00', name: '核心', verb: '形成', prompt: '意识并未完成。它只是在此刻形成。' },
      { id: 'observe', index: '01', name: '观象', verb: '我看见了什么', prompt: '表象是入口，不是结论。' },
      { id: 'order', index: '02', name: '构序', verb: '我如何理解它', prompt: '知识在关系中获得形状。' },
      { id: 'inward', index: '03', name: '观心', verb: '世界如何穿过我', prompt: '时间使同一个问题拥有不同的重量。' },
      { id: 'reflect', index: '04', name: '见性', verb: '剥离之后仍留下什么', prompt: '越深入，越澄明。' },
    ],
    themes: [
      { id: 'systems', label: '系统边界' },
      { id: 'evidence', label: '证据' },
      { id: 'human-ai', label: '人机协作' },
      { id: 'time', label: '时间' },
      { id: 'choice', label: '选择' },
      { id: 'authenticity', label: '本真' },
    ],
    articles: [
      {
        id: 'agent-architecture',
        title: '从“能回答”到“能交付”：生产级 AI Agent 的五层工程架构',
        shortTitle: '从能回答，到能交付',
        date: '2026-07-11',
        year: '2026',
        kind: '技术实践',
        status: '已发布',
        prototype: false,
        layer: 'observe',
        depth: 2,
        minutes: 13,
        themes: ['systems', 'evidence', 'human-ai'],
        summary: '模型处理模糊性，系统保存状态、约束风险并提供证据；可靠性本身就是用户正在使用的产品。',
        excerpt: '这些问题的答案不在一条更长的 Prompt 里。生产级 Agent 的本质，是一套以模型为推理部件、以确定性工程为安全边界的执行系统。',
        paragraphs: [
          '一个大模型接上聊天框，很快就能做出“像 Agent”的演示。但当系统真正进入业务流程，检索时效、工具超时、重复副作用与人工接管会让问题突然变得具体。',
          '模型负责处理模糊性，系统负责约束风险、保存状态、提供证据，并让每一步都可以恢复和解释。任何一层接近零，整体交付能力都会失效。',
          '当 Agent 开始改变外部状态时，可靠性不再是后台工程细节——它本身就是用户正在使用的产品。',
        ],
      },
      {
        id: 'aigc-revolution',
        title: 'AIGC：人工智能生成内容的革命',
        shortTitle: 'AIGC 与创造的边界',
        date: '2023-06-15',
        year: '2023',
        kind: '外部观察',
        status: '已发布',
        prototype: false,
        layer: 'observe',
        depth: 1,
        minutes: 6,
        themes: ['human-ai', 'choice'],
        summary: '回看生成式技术如何改变创作效率、版权边界与人类创作者的位置。',
        excerpt: '未来，人类创作者和 AI 将如何协作，共同推动内容创新，是一个值得持续关注和探索的话题。',
        paragraphs: [
          '人工智能生成内容正在重塑我们创造和消费内容的方式。生成速度、成本与规模带来了效率，也把版权、伦理与人的位置推到新的边界。',
          '技术并不替我们完成判断。真正值得持续观察的，是人类创作者如何与生成系统协作，又如何保留不可外包的选择。',
        ],
      },
      {
        id: 'docker-standards',
        title: 'Docker in 2024: Evolving Relevance in Modern DevOps',
        shortTitle: '当颠覆者成为标准',
        date: '2024-09-17',
        year: '2024',
        kind: '技术观察',
        status: '已发布',
        prototype: false,
        layer: 'order',
        depth: 2,
        minutes: 9,
        themes: ['systems', 'time'],
        summary: 'Docker 从颠覆性工具变成基础设施标准，也提醒我们：价值会随着生态关系重新定义。',
        excerpt: 'Docker’s role has adapted rather than diminished. Its long-term value lives in the standards and workflows it helped make ordinary.',
        paragraphs: [
          'Docker 把容器带入主流，又通过 OCI 等开放标准让自身变得可替代。它的价值不再只属于一个工具，而被重新分布到整个生态。',
          '一项技术从“新”走向“普通”的过程，也是理解系统关系的过程：形式会过时，解决过的问题与建立的标准仍然留下。',
        ],
      },
      {
        id: 'evidence-before-answer',
        title: '从答案退回证据：我的知识校准方法',
        shortTitle: '从答案退回证据',
        date: '2025-11-03',
        year: '2025',
        kind: '知识方法论',
        status: '原型内容 · 待作者确认',
        prototype: true,
        layer: 'order',
        depth: 3,
        minutes: 8,
        themes: ['evidence', 'systems', 'choice'],
        summary: '把“我相信什么”拆回来源、时间、反例与行动后果，让知识保持可修订。',
        excerpt: '我不再从结论开始整理知识，而是先保存它依赖的证据、失效条件与当时的观察位置。',
        paragraphs: [
          '这是一篇为原型编写、等待作者确认的内容。它不代表作者已经发生过的具体经历。',
          '知识的秩序不来自收藏更多答案，而来自知道一个判断依赖什么证据、在哪个时间有效、遇到什么反例就应被改写。',
          '当结论可以退回来源，它就不再需要被防卫；它只是当前视角下，仍愿意承担后果的一次判断。',
        ],
      },
      {
        id: 'efficiency-silence',
        title: '当效率不再回答我',
        shortTitle: '效率没有回答的部分',
        date: '2022-08-19',
        year: '2022',
        kind: '个人觉察',
        status: '原型内容 · 待作者确认',
        prototype: true,
        layer: 'inward',
        depth: 4,
        minutes: 7,
        themes: ['choice', 'time', 'authenticity'],
        summary: '一次关于速度、价值与自我要求的停顿：完成得更多，并没有自动回答为何出发。',
        excerpt: '我擅长让事情继续向前，却在某个晚上第一次承认：推进并不等于抵达。',
        paragraphs: [
          '这是一篇为原型编写、等待作者确认的内容。它不代表作者已经发生过的具体经历。',
          '有一段时间，完成本身几乎成了唯一的衡量方式。速度带来确定感，也让没有被回答的问题更容易被推迟。',
          '停下来并没有立刻给出方向。它只是让我承认：推进不等于抵达，而真正的选择往往从不再自动前进开始。',
        ],
      },
      {
        id: 'unnamed-real',
        title: '未被命名之前',
        shortTitle: '未被命名之前',
        date: '2026-06-21',
        year: '2026',
        kind: '本真 / 见性',
        status: '原型内容 · 待作者确认',
        prototype: true,
        layer: 'reflect',
        depth: 5,
        minutes: 5,
        themes: ['authenticity', 'time'],
        summary: '身份、能力与判断暂时退去后，仍有一部分经验不能被替代，也不急于获得名称。',
        excerpt: '最深处并没有答案。只是有些东西在所有解释退去之后，仍然要求我亲自面对。',
        paragraphs: [
          '这是一篇为原型编写、等待作者确认的内容。它不代表作者已经形成的哲学结论。',
          '我们用身份、能力和判断让自己变得可以解释，也在解释中逐渐忘记：有些经验在获得名称之前，已经真实地发生。',
          '最深处没有标准答案。只是有些东西在所有解释退去之后，仍然要求我亲自面对。',
        ],
      },
    ],
    relations: [
      { from: 'aigc-revolution', to: 'agent-architecture', type: '跨时间', label: '从生成内容到改变现实状态', years: '2023 → 2026', trigger: 'dwell' },
      { from: 'docker-standards', to: 'agent-architecture', type: '系统', label: '标准如何成为可靠性的边界', years: '2024 → 2026' },
      { from: 'evidence-before-answer', to: 'agent-architecture', type: '证据', label: '知识校准进入工程执行', years: '2025 → 2026' },
      { from: 'efficiency-silence', to: 'evidence-before-answer', type: '选择', label: '从自动推进到主动校准', years: '2022 → 2025' },
      { from: 'efficiency-silence', to: 'unnamed-real', type: '跨时间', label: '同一个未回答的问题再次出现', years: '2022 → 2026', trigger: 'dwell' },
      { from: 'aigc-revolution', to: 'evidence-before-answer', type: '判断', label: '面对新技术时保存反例', years: '2023 → 2025' },
      { from: 'docker-standards', to: 'evidence-before-answer', type: '方法', label: '从工具结论退回生态关系', years: '2024 → 2025' },
      { from: 'agent-architecture', to: 'unnamed-real', type: '边界', label: '系统可交付，选择不可外包', years: '2026' },
      { from: 'aigc-revolution', to: 'unnamed-real', type: '人机', label: '生成能力与不可替代之物', years: '2023 → 2026' },
      { from: 'evidence-before-answer', to: 'unnamed-real', type: '剥离', label: '当所有结论都可以被修订', years: '2025 → 2026' },
    ],
    reflectionQuestions: [
      '当所有可证明的部分都退去，你仍愿意为哪一个选择负责？',
      '你正在寻找答案，还是在寻找一个不必再改变自己的理由？',
      '如果效率不再替你定义方向，你会停在哪一个尚未命名的问题前？',
      '哪些你以为已经过去的困惑，仍在决定今天的观察位置？',
    ],
  }

  window.SELF_AWAKE_CONTENT = content
})()

